name: RSpec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: utmb_trail_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d utmb_trail_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DISABLE_SPRING: "1"
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/utmb_trail_test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"
          bundler-cache: true

      - name: Prepare database
        run: bundle exec rails db:prepare

      - name: Run RSpec
        run: bundle exec rspec
